project_id = "ydlxjdraipgmqewwlqdb"

[functions.generate-pdf]
verify_jwt = false

[functions.generate-word]
verify_jwt = false

[functions.ai-enhance]
verify_jwt = true

[functions.ai-job-match]
verify_jwt = true

[functions.ai-translate]
verify_jwt = true

[functions.create-checkout-session]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false